name: test
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-sqlite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - oldstable
          - stable
    name: "test-sqlite (go: ${{ matrix.go }})"
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: go version
        run: go version
      - name: print
        run: |
          go run . --dir ./internal/example/ent/schema --dev="sqlite3://test?_fk=1" > internal/example/ent/sqlite3.hcl
          cat internal/example/ent/sqlite3.hcl
          rm test
      - name: verify no diff
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo "diff between generated hcl file and checked in file"
            echo "$status"
            git diff
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerize: [true, false]
        db: [mysql, postgres]
        include:
          - db: mysql
            url: "mysql://root:pass@localhost:3307/test"
            tag: "8.0.29"
            schema: test
          - db: postgres
            url: "postgres://postgres:pass@localhost:5432/test?sslmode=disable"
            tag: "14"
            schema: default
    name: "test-${{ matrix.db}} (dockerize: ${{ matrix.dockerize }})"
    services:
      mysql:
        image: mysql:8.0.29
        env:
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_DATABASE: test
        ports:
          - "3307:3306"
        options: >-
          --health-cmd "mysqladmin ping -ppass"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
      postgres14:
        image: postgres:14
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-go@v3
        with:
          go-version: stable
      - uses: actions/cache@v3.0.6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: print
        if: ${{ !matrix.dockerize }}
        run: |
          go run . --dir ./internal/example/ent/schema --dev ${{ matrix.url }} > internal/example/ent/${{ matrix.db }}.hcl
          cat internal/example/ent/${{ matrix.db }}.hcl
      - name: print
        if: ${{ matrix.dockerize }}
        run: |
          go run . --dir ./internal/example/ent/schema --dev docker://${{ matrix.db }}/${{ matrix.tag }}/${{ matrix.schema }} > internal/example/ent/${{ matrix.db }}.hcl
          cat internal/example/ent/${{ matrix.db }}.hcl
      - name: verify no diff
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo "diff between generated hcl file and checked in file"
            echo "$status"
            git diff
            exit 1
          fi
