name: test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db: [mysql, postgres]
        include:
          - db: mysql
            url: "mysql://root:pass@localhost:3307/test"
          - db: postgres
            url: "postgres://postgres:pass@localhost:5432/test?sslmode=disable"
    services:
      mysql:
        image: mysql:8.0.29
        env:
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_DATABASE: test
        ports:
          - "3307:3306"
        options: >-
          --health-cmd "mysqladmin ping -ppass"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 1
      postgres14:
        image: postgres:14
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: pass
        ports:
          - 5434:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/cache@v2.1.6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: print
        run: |
          go run . --dir ./internal/example/ent/schema --dev ${{ matrix.url}} > internal/example/ent/${{ matrix.db }}.hcl
          cat internal/example/ent/${{ matrix.db }}.hcl
      - name: verify no diff
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo "diff between generated hcl file and checked in file" 
            echo "$status"
            git diff
            exit 1
          fi
